# Generated by Django 3.1.5 on 2022-04-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveDirectoryConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.CharField(max_length=255)),
                ('tenant_id', models.CharField(max_length=255)),
                ('mirror_groups', models.BooleanField(default=True)),
                ('groups_claim', models.CharField(choices=[('roles', 'Directory Roles'), ('groups', 'Security Groups')], default='roles', max_length=255)),
                ('username_claim', models.CharField(choices=[('upn', 'UPN')], default='upn', max_length=255)),
            ],
            options={
                'verbose_name': 'Active Directory config',
                'verbose_name_plural': 'Active Directory config',
            },
        ),
    ]
