# Generated by Django 3.2.9 on 2021-11-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_auth_adfs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activedirectoryconfig',
            options={'verbose_name': 'Active Directory config', 'verbose_name_plural': 'Active Directory config'},
        ),
        migrations.AlterField(
            model_name='activedirectoryconfig',
            name='client_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activedirectoryconfig',
            name='client_secret',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activedirectoryconfig',
            name='enabled',
            field=models.BooleanField(default=False, verbose_name='Enable/Disable Active Directory use'),
        ),
        migrations.AlterField(
            model_name='activedirectoryconfig',
            name='tenant_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
